server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled:
            true
      routes:
        - id: chirps
          uri: http://localhost:8090
          predicates:
            -  Path=/api/v1/chirps/**
        - id: users
          uri: http://localhost:8070
          predicates:
            -  Path=/api/v1/users/**
  config:
    import: optional:configserver:asd
